### ISSUE TITLE
Autocomplete Issues

### ISSUE THREAD

**Issue by GlitchMC** [aturfah/eou-grimoire-editor#10]
The autocomplete feature is nice, but it's also a bit buggy. Typing names too fast sometimes causes it to autocomplete a name and then continue to enter your text at the end of the name, even if it was wrong (ex. i was typing "Corrosive" and it autocompleted "Coconut Cannon" and put the "rr" at the end of the autocompleted skill. 

Would it be possible to treat the text field as a search bar, and populate possible matches in a dropdown directly under the box, so that not only would you be able to see all current possible matches, but also click/arrow down to the skill you're trying to pick?
A good example of this function is from the Pokemon Showdown Calculator https://calc.pokemonshowdown.com/

**Comment by aturfah** [comment]
Hey @GlitchMC sorry for the delay in responding but I appreciate you submitting issues here.

In truth this project was my first time using the python `tkinter` module and I was having a lot of trouble with it, and you'll notice for the [EO2U grimoire editor](https://github.com/aturfah/eo2u-grimoire-editor) I switched to using a web interface. It is my intention to redo the UI for this one using that set-up, since the codebase is mostly the same this shouldn't be too difficult.

Now its just a matter of finding the time to do that...

**Comment by GlitchMC** [comment]
no worries; i hadn't used the U2 editor yet tbh since i hadn't started working on that project for myself lol but i'll check it out and see what to look forward to!

**Comment by aturfah** [comment]
Addressed in #12
